CREATE TABLE "Rubrics" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(80) NOT NULL,
    "Description" text NULL,
    "TimePublished" timestamp with time zone NULL,
    "IsObsolete" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Rubrics" PRIMARY KEY ("Id")
);

CREATE TABLE "RubricCriteria" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(80) NOT NULL,
    "Description" text NULL,
    "RubricId" integer NOT NULL,
    "Index" integer NOT NULL,
    CONSTRAINT "PK_RubricCriteria" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RubricCriteria_Rubrics_RubricId" FOREIGN KEY ("RubricId") REFERENCES "Rubrics" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RubricRatings" (
    "CriterionId" integer NOT NULL,
    "Index" integer NOT NULL,
    "Value" double precision NULL,
    "Description" text NULL,
    CONSTRAINT "PK_RubricRatings" PRIMARY KEY ("CriterionId", "Index"),
    CONSTRAINT "FK_RubricRatings_RubricCriteria_CriterionId" FOREIGN KEY ("CriterionId") REFERENCES "RubricCriteria" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_RubricCriteria_RubricId" ON "RubricCriteria" ("RubricId");

DELETE FROM "__EFMigrationsHistory";
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20220924053248_InitialSchema', '6.0.9');
