ALTER TABLE "Courses" DROP COLUMN "AbetDescriptionId";
ALTER TABLE "Courses" ADD COLUMN "CourseJournalId" integer NULL;

CREATE TABLE "CourseJournals" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CourseId" integer NOT NULL,
    "Term_Code" integer NULL,
    "InstructorId" integer NOT NULL,
    "CourseUrl" character varying(255) NOT NULL,
    "SyllabusUrl" character varying(255) NOT NULL,
    CONSTRAINT "PK_CourseJournals" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CourseJournals_Persons_InstructorId" FOREIGN KEY ("InstructorId") REFERENCES "Persons" ("Id") ON DELETE CASCADE
);

CREATE TABLE "StudentSamples" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CourseJournalId" integer NOT NULL,
    "Name" character varying(255) NOT NULL,
    "Url" character varying(255) NOT NULL,
    "Grade" character varying(255) NULL,
    CONSTRAINT "PK_StudentSamples" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StudentSamples_CourseJournals_CourseJournalId" FOREIGN KEY ("CourseJournalId") REFERENCES "CourseJournals" ("Id") ON DELETE CASCADE
);

ALTER TABLE "Courses" ADD CONSTRAINT "FK_Courses_CourseJournals_CourseJournalId" FOREIGN KEY ("CourseJournalId") REFERENCES "CourseJournals" ("Id");

ALTER TABLE "CourseJournals" ADD CONSTRAINT "FK_CourseJournals_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES "Courses" ("Id") ON DELETE CASCADE;

CREATE INDEX "IX_CourseJournals_CourseId" ON "CourseJournals" ("CourseId");

CREATE INDEX "IX_CourseJournals_InstructorId" ON "CourseJournals" ("InstructorId");

CREATE UNIQUE INDEX "IX_Courses_CourseJournalId" ON "Courses" ("CourseJournalId");

CREATE INDEX "IX_StudentSamples_CourseJournalId" ON "StudentSamples" ("CourseJournalId");
