CREATE TABLE "Surveys" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" text NULL,
    "TimeCreated" timestamp with time zone NOT NULL,
    "TimePublished" timestamp with time zone NULL,
    "TimeClosed" timestamp with time zone NULL,
    "QuestionCount" integer NOT NULL,
    "ResponseCount" integer NOT NULL,
    "AllowMultipleSubmissions" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Surveys" PRIMARY KEY ("Id")
);

CREATE TABLE "SurveyQuestions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Type" character varying(10) NOT NULL,
    "Description" text NULL,
    "SurveyId" integer NOT NULL,
    "Index" integer NOT NULL,
    "IncludeNotApplicable" boolean NOT NULL,
    "TextLength" integer NOT NULL,
    "MinRating" integer NOT NULL,
    "MaxRating" integer NOT NULL,
    "Choices" text NULL,
    "MinSelection" integer NOT NULL,
    "MaxSelection" integer NOT NULL,
    CONSTRAINT "PK_SurveyQuestions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SurveyQuestions_Surveys_SurveyId" FOREIGN KEY ("SurveyId") REFERENCES "Surveys" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SurveyResponses" (
    "Id" uuid NOT NULL,
    "SurveyId" integer NOT NULL,
    "TimeSubmitted" timestamp with time zone NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_SurveyResponses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SurveyResponses_Surveys_SurveyId" FOREIGN KEY ("SurveyId") REFERENCES "Surveys" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SurveyAnswers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "QuestionId" integer NOT NULL,
    "ResponseId" uuid NOT NULL,
    "Text" text NULL,
    "Rating" integer NULL,
    "NotApplicable" boolean NOT NULL,
    "Selections" text NULL,
    CONSTRAINT "PK_SurveyAnswers" PRIMARY KEY ("Id"),
    CONSTRAINT "AK_SurveyAnswers_ResponseId_QuestionId" UNIQUE ("ResponseId", "QuestionId"),
    CONSTRAINT "FK_SurveyAnswers_SurveyQuestions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "SurveyQuestions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SurveyAnswers_SurveyResponses_ResponseId" FOREIGN KEY ("ResponseId") REFERENCES "SurveyResponses" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_SurveyQuestions_SurveyId_Index" ON "SurveyQuestions" ("SurveyId", "Index");

CREATE INDEX "IX_SurveyAnswers_QuestionId" ON "SurveyAnswers" ("QuestionId");

CREATE INDEX "IX_SurveyResponses_SurveyId" ON "SurveyResponses" ("SurveyId");

DELETE FROM "__EFMigrationsHistory";
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20220802215654_InitialSchema', '6.0.7');
